##
## Makefile for 103Architect in /home/bender/Repo/103architect
##
## Made by Junior Bender
## Login   <bender@epitech.net>
##
## Started on  Tue Dec  6 19:02:38 2016 Junior Bender
## Last update Tue Dec 13 10:13:49 2016 John Doe
##

NAME	= 103architect

SRCS	= srcs/*.c					\
				srcs/ops/*.c			\
				srcs/struct/*.c

all:
	clang $(SRCS) -g -lm -o $(NAME)
